version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/Scrubx.Desktop
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /tests/Scrubx.Tests
    schedule:
      interval: weekly
